### ISSUE TITLE
[Bug]Permissions for app not work

### ISSUE THREAD

**Issue by anyidea** [casdoor/casdoor#2388]
![F817B920-43DD-4DC0-94F1-E347AFFF721D](https://github.com/casdoor/casdoor/assets/48710760/d24c5116-78b3-490e-8560-5debdab07d4d)

Case 1: If i grant access permission to someone for app SRM, all users can login that app.
Case 2: If i deny someone to access app SRM, all users cannot login that app.

Version: v1.428.0

**Comment by anyidea** [comment]
> @anyidea your video shows nothing.
> 
> Here're the rules:
> 
> 1. By default allow all
> 2. If one allow permission exists, all others will be auto denied.
> 3. If deny permission exists, all others still allow

I known the rules,

**Comment by hsluoyz** [comment]
@anyidea fixed by: https://github.com/casdoor/casdoor/commit/ec0a8e16f7802d7a81413a772b71f3c3f5822da1

**Comment by anyidea** [comment]
@hsluoyz permissions for users is ok, but for roles still not work
