### ISSUE TITLE
The model  for permission is not found

### ISSUE THREAD

**Issue by agedcat** [casdoor/casdoor#2437]
organization: homeserver
model:
![image](https://github.com/casdoor/casdoor/assets/76728773/0e271e0e-d0e6-4bc7-be2e-56780d122f93)

When I create a permission, a error occured.

![image](https://github.com/casdoor/casdoor/assets/76728773/ae8d87db-ed07-4752-8228-a41a31c92140)

**Comment by hsluoyz** [comment]
@agedcat fixed by: https://github.com/casdoor/casdoor/commit/ee3b46e91c62e3ab66fafc61834cc1d50175e7f7

First, change org to your org, here click Save.

Then change model to your org's model, click Save again.

You cannot change org and model at the same time, or there will be error.

**Comment by agedcat** [comment]
@hsluoyz org and model has been setted, the error still existed.
Finally, I find out the reason: data synchronization takes time.
Thanks,bro.
