### ISSUE TITLE
Unable to start the container using the Docker image from casbin/casdoor:v1.789.0 (inclusive) onwards.

### ISSUE THREAD

**Issue by Sun-drenched** [casdoor/casdoor#3485]
When using the Docker image `casbin/casdoor:v1.789.0` (inclusive) and later versions, the container logs show errors upon startup.

[xorm] [warn] 2025/01/09 02:45:05.524776 Table verification_record Column is_used db nullable is true, struct nullable is false
panic: strconv.Atoi: parsing "/server": invalid syntax

goroutine 1 [running]:
main.main()
/go/src/casdoor/main.go:88 +0x585

————————————————————————————————————————————————————————————
When using the Docker image `casbin/casdoor:v1.789.0` (exclusive) and earlier versions, the container logs upon startup are as follows.

[xorm] [warn]  2025/01/09 03:37:45.957653 Table user has column kwai but struct has not related field
[xorm] [warn]  2025/01/09 03:37:46.169510 Table verification_record Column is_used db nullable is true, struct nullable is false
2025/01/09 03:37:46 Listening on 0.0.0.0:389
2025/01/09 03:37:46 Starting Radius server on 0.0.0.0:1812
2025/01/09 03:37:46.300 [I]  http server Running on http://:8000

————————————————————————————————————————————————————————————
The database container image used is `pgvector:pg16`.

**Comment by hsluoyz** [comment]
@Sun-drenched it has been fixed in latest version (now is: v1.792.0)

**Comment by Lelenaic** [comment]
Still have the issue here with v1.792.0 or with the current latest v1.822.0.

**Comment by hsluoyz** [comment]
@Lelenaic can you find out starting from which version this issue happens? aka the Pull Request that causes this issue
