### ISSUE TITLE
When a regular Casdoor user logs into the application and clicks "My Account," the message "Failed to load: Unauthorized operation" appears.

### ISSUE THREAD

**Issue by wangweiningse** [casdoor/casdoor#4405]
When a regular Casdoor user logs into the application and clicks "My Account," the message "Failed to load: Unauthorized operation" appears.

<img width="1920" height="900" alt="Image" src="https://github.com/user-attachments/assets/da5eeeda-b238-4ab8-b2eb-8e8d54d0ac9e" />

<img width="1920" height="258" alt="Image" src="https://github.com/user-attachments/assets/82ee583b-3710-4b96-be0b-dd9eafe41548" />

**Comment by hsluoyz** [comment]
fixed in latest version

**Comment by wangweiningse** [comment]
> fixed in latest version

@hsluoyz I just tested it on the demo site, and the problem still occurs.

<img width="1920" height="255" alt="Image" src="https://github.com/user-attachments/assets/a664aa33-647d-428c-a022-9d138831d2e7" />
