### ISSUE TITLE
Keycloak Syncer Issue - Syncer failed to sync users: SyntaxError: Unexpected token < in JSON at position 1

### ISSUE THREAD

**Issue by billyhu** [casdoor/casdoor#880]
I have launched keycloak  "quay.io/keycloak/keycloak:legacy", postgres and casdoor "casbin/casdoor-all-in-one" with docker image, and tried to sync users with keycloak syncer in casdoor.
I followed this doc to config keycloak syncer - https://casdoor.org/docs/syncer/Keycloak#keycloak-syncer, 
and got below error message when triggering syncer
Syncer failed to sync users: SyntaxError: Unexpected token < in JSON at position 1

**Comment by hsluoyz** [comment]
@seriouszyx

**Comment by seriouszyx** [comment]
@billyhu We fixed the dataSource for PostgreSQL and some detailed problems where the Keycloak table fields in the PostgrSQL are all lowercase. plz review https://github.com/casdoor/casdoor/pull/886

**Comment by billyhu** [comment]
Thanks @seriouszyx  and @hsluoyz. 
I have tried to sync users with the latest image of casdoor,  there's no error message now, while it seems users are still not inserted into the table casdoor.user, so we cannot see users list on the page. could you please have a check on this issue?

**Comment by billyhu** [comment]
sure, thanks.
